### ISSUE TITLE
A problem in making KB_GF_CONVOLUTE.f90.o

### ISSUE THREAD

**Issue by dirichlet10** [QcmPlab/KB_GF#1]
I run the cmake successfully. But I run into an error in making KB_GF_CONVOLUTE.f90.o. Is it caused by my old version of compiler? Thanks in advance.

-- OS: Linux 3.10.0-693.el7.x86_64
-- BUILD_TYPE=RELEASE
-- Set Fortran compiler FC to /public/software_purley/mpi/intelmpi/2017.4.239/intel64/bin/mpiifort, ID=Intel
-- Checking for one of the modules 'scifor'
-- SCIFOR found at: /public/home/gengl/A_LIB/SciFortran/scifor/intel/4.7.12
-- Fortran Compiler id   = Intel
-- Fortran Compiler ver. = 17.0.5.20170817
-- Fortran Compiler options = -fpp -O3 -ftz
-- release
-- intel/master
-- Module file: kb_gf/user_prefix/intel/master/0.0.1
-- Library version: 0.0.1
-- Library will be installed in: /public/home/gengl/A_LIB/KB_GF/kb_gf/intel/master/0.0.1
--
>> TO CONCLUDE INSTALLATION <<
Compile with:
$ gmake
Install with:
$ gmake install

Uninstall with:
$ gmake uninstall

-- Configuring done
-- Generating done
-- Build files have been written to: /public/home/gengl/A_LIB/package/KB_GF-main/build

Scanning dependencies of target KB_LIBRARY
[  7%] Building Fortran object src/CMakeFiles/KB_LIBRARY.dir/KB_VERSION.f90.o
[ 14%] Building Fortran object src/CMakeFiles/KB_LIBRARY.dir/KB_VARS_GLOBAL.f90.o
[ 21%] Building Fortran object src/CMakeFiles/KB_LIBRARY.dir/KB_CONTOUR.f90.o
[ 28%] Building Fortran object src/CMakeFiles/KB_LIBRARY.dir/KB_AUX.f90.o
[ 35%] Building Fortran object src/CMakeFiles/KB_LIBRARY.dir/KB_GF_COMMON.f90.o
[ 42%] Building Fortran object src/CMakeFiles/KB_LIBRARY.dir/KB_GF_CONVOLUTE.f90.o
/public/home/gengl/A_LIB/package/KB_GF-main/src/KB_GF_CONVOLUTE.f90: catastrophic error: **Internal compiler error: internal abort** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
compilation aborted for /public/home/gengl/A_LIB/package/KB_GF-main/src/KB_GF_CONVOLUTE.f90 (code 1)
make[2]: *** [src/CMakeFiles/KB_LIBRARY.dir/KB_GF_CONVOLUTE.f90.o] Error 1
make[1]: *** [src/CMakeFiles/KB_LIBRARY.dir/all] Error 2
make: *** [all] Error 2

**Comment by aamaricci** [comment]
It might be well related to the compiler version, as this library makes use of some Fortran 20xy features which might not be avail with older compiler. 
Please note that this library is still under development and, so far, I am not able to check supported compilers nor to state it is bug free.
